"""Add Post and Comment models, dynamic achievement fields

Revision ID: 045839bacf49
Revises: 1f3cb62d23e4
Create Date: 2025-10-27 18:19:15.922500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '045839bacf49'
down_revision = '1f3cb62d23e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('achievements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('threshold_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('threshold_value', sa.Float(), nullable=True))

    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.alter_column('date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('solution')
        batch_op.drop_column('problem')
        batch_op.drop_column('category')

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_created', sa.DateTime(), nullable=True))
        batch_op.drop_column('timestamp')

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_created', sa.DateTime(), nullable=True))
        batch_op.drop_column('timestamp')
        batch_op.drop_column('title')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.VARCHAR(length=200), nullable=False))
        batch_op.add_column(sa.Column('timestamp', sa.DATETIME(), nullable=True))
        batch_op.drop_column('date_created')

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.DATETIME(), nullable=True))
        batch_op.drop_column('date_created')

    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('problem', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('solution', sa.TEXT(), nullable=True))
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)

    with op.batch_alter_table('achievements', schema=None) as batch_op:
        batch_op.drop_column('threshold_value')
        batch_op.drop_column('threshold_type')

    # ### end Alembic commands ###
